### PR TITLE
Multiphase support

### PR DESCRIPTION
**Pull request by ksemb**
This PR implements multiphase support (interFoam and multiphaseInterFoam).

The material names and the names of the phase fraction regions are specified using the object label.

dambreak

### CODE REVIEW

**Comment by oliveroxtoby** [comment]
This looks fantastic, thank you for the contribution! I am just making a few consistency tweaks and will merge shortly. 

Can we acknowledge the contribution in the Readme? Please supply your details.

**Comment by ksemb** [comment]
I added some error checks in the meantime.
> Can we acknowledge the contribution in the Readme? Please supply your details.

Yes, thank you. My name is Klaus Sembritzki

**Comment by oliveroxtoby** [comment]
I have integrated the branch. At the moment it is in the 'multiphase' branch while we do a bit of testing.

There are a few deviations from your code:
- Used the material names rather than the alpha zone names as the names of the phases, since one can have multiple phases without corresponding setFields regions.
- Changed alpha zones to be a more general interface to setFields

We have a few limitations:
- Need to be able to specify inlet alpha values - at the moment the initial field values are used, which is tolerable for now as an initialisation zone can be used as a workaround
- Need to be able to set g, but reasonable to fix at -9.81 in the y direction for now
- Need to be able to set surface tension. For now I am defaulting to 0.0 as I would rather not model it at all than for the water value everywhere.

Thanks again for the contribution, and feel free to continue from here based on the multiphase branch.

**Comment by oliveroxtoby** [comment]
Multiphase branch is now merged into master and removed

**Pull request closed without merging**
